### ISSUE TITLE
KeyError: entity_start_name

### ISSUE THREAD

**Issue by andreasropel** [Hellowlol/chargebot#2]
Hi. Tried to start charge_bot via AppDaemon4 and got this error. I cannot see what is being wrong or if I missed anything:

`2021-09-20 12:45:35.206854 WARNING charge_bot: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 903, in worker
    funcref(
  File "/config/appdaemon/apps/chargebot.py", line 722, in load_balance_cb
    self.check_load(new)
  File "/usr/lib/python3.9/site-packages/appdaemon/adbase.py", line 33, in f_app_lock
    return f(*args, **kw)
  File "/config/appdaemon/apps/chargebot.py", line 607, in check_load
    esn = self.args["entity_start_name"]
KeyError: 'entity_start_name'
2021-09-20 12:45:35.207125 WARNING charge_bot: ------------------------------------------------------------`

What it is needed for?

**Comment by Hellowlol** [comment]
Its used to find the correct sensors for your easee charger. For me its easee_home_38502

**Comment by andreasropel** [comment]
Thanks for reply! I figured out. My Easee is name EH7XXXXX. 
Which integration are you using for Easee home? I am using [fondberg’s](https://github.com/fondberg/easee_hass/) integration and it seems some of the sensors have been renamed?! Is your code up to date accordingly to the sensor names given by fondberg’s integration? Haven’t yet got it working.

**Comment by Hellowlol** [comment]
I think it should work. My tesla integration is broken so it hasnt worked for a long time (havnt updated ha for a while so it fails to get soc.) just enable logging and make a new issue with the logs if something is broken
